### ISSUE TITLE
working with angular 1.4.x

### ISSUE THREAD

**Issue by dohomi** [sayanee/angularjs-pdf#58] opened 2015-10-27 19:06 UTC
Hello,

I would like to know if this plugin works with Angular 1.4?

Best,
Dominic

**Comment by dohomi** [comment] 2015-10-27 19:15
So far it works pretty well, would be nice if you could adjust your bower file. Cheers!

**Comment by sayanee** [comment] 2015-10-28 09:14
:+1: will upgrade to Angular `1.4.x` by this week and make a release

**Comment by dohomi** [comment] 2015-10-28 09:34
Nice!

**Comment by sayanee** [comment] 2015-10-31 04:20
closed with fea08d92c01dda023c95c775bd46e04440d2091a and tagged [1.2.1](https://github.com/sayanee/angularjs-pdf/releases/tag/1.2.1)

**Comment by banbanchs** [comment] 2015-12-24 02:21
@sayanee Hi, just want to ask a small question: why use `1.4.7` instead of `~1.4.7`? My project use angular 1.4.5 and can not install it because of the version.

**Comment by sayanee** [comment] 2015-12-24 08:37
Yes we should do that. Could you paste the command and the error notes?

**Comment by banbanchs** [comment] 2015-12-24 09:56
@sayanee 

```
bower angular-pdf#*             cached git://github.com/sayanee/angularjs-pdf.git#1.2.9
bower angular-pdf#*           validate 1.2.9 against git://github.com/sayanee/angularjs-pdf.git#*
bower angular#1.4.8             cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#1.4.8           validate 1.4.8 against git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.2.0           cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.2.0         validate 1.4.8 against git://github.com/angular/bower-angular.git#>=1.2.0
bower angular#*                 cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#*               validate 1.4.8 against git://github.com/angular/bower-angular.git#*
bower angular#~1.3              cached git://github.com/angular/bower-angular.git#1.3.20
bower angular#~1.3            validate 1.3.20 against git://github.com/angular/bower-angular.git#~1.3
bower angular#~1.x              cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#~1.x            validate 1.4.8 against git://github.com/angular/bower-angular.git#~1.x
bower angular#>= 1.0.8          cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>= 1.0.8        validate 1.4.8 against git://github.com/angular/bower-angular.git#>= 1.0.8
bower angular#>=1.2.18          cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.2.18        validate 1.4.8 against git://github.com/angular/bower-angular.git#>=1.2.18
bower angular#>=1.2.16 <=1.3.16 cached git://github.com/angular/bower-angular.git#1.3.16
bower angular#>=1.2.16 <=1.3.16         validate 1.3.16 against git://github.com/angular/bower-angular.git#>=1.2.16 <=1.3.16
bower angular#~1.4.0                      cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#~1.4.0                    validate 1.4.8 against git://github.com/angular/bower-angular.git#~1.4.0
bower angular#^1.2                        cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#^1.2                      validate 1.4.8 against git://github.com/angular/bower-angular.git#^1.2
bower angular#~1.4.5                      cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#~1.4.5                    validate 1.4.8 against git://github.com/angular/bower-angular.git#~1.4.5
bower angular#>=1.3.0                     cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.3.0                   validate 1.4.8 against git://github.com/angular/bower-angular.git#>=1.3.0
bower angular#>=1.2.26 <=1.5              cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.2.26 <=1.5            validate 1.4.8 against git://github.com/angular/bower-angular.git#>=1.2.26 <=1.5
bower angular#~1                          cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#~1                        validate 1.4.8 against git://github.com/angular/bower-angular.git#~1
bower angular#^1.4.5                      cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#^1.4.5                    validate 1.4.8 against git://github.com/angular/bower-angular.git#^1.4.5
bower angular#>= 1.2.0                    cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>= 1.2.0                  validate 1.4.8 against git://github.com/angular/bower-angular.git#>= 1.2.0
bower angular#>=1.1.4                     cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.1.4                   validate 1.4.8 against git://github.com/angular/bower-angular.git#>=1.1.4
bower angular#1.4.6                       cached git://github.com/angular/bower-angular.git#1.4.6
bower angular#1.4.6                     validate 1.4.6 against git://github.com/angular/bower-angular.git#1.4.6
bower angular#>=1.3.x                     cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.3.x                   validate 1.4.8 against git://github.com/angular/bower-angular.git#>=1.3.x
bower angular#>= 1.1.5                    cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#>= 1.1.5                  validate 1.4.8 against git://github.com/angular/bower-angular.git#>= 1.1.5
bower angular#^1.2.6                      cached git://github.com/angular/bower-angular.git#1.4.8
bower angular#^1.2.6                    validate 1.4.8 against git://github.com/angular/bower-angular.git#^1.2.6
bower angular#1.4.3                       cached git://github.com/angular/bower-angular.git#1.4.3
bower angular#1.4.3                     validate 1.4.3 against git://github.com/angular/bower-angular.git#1.4.3
bower                                  ECONFLICT Unable to find suitable version for angular
```

bower.json
```json
{
  "version": "0.1.0",
  "dependencies": {
    "angular": "1.4.5",
    "angucomplete-alt": "~1.1.0",
    "angular-animate": "1.4.5",
    "angular-cookies": "1.4.5",
    "angular-messages": "1.4.5",
    "angular-sanitize": "1.4.5",
    "angular-i18n": "1.4.5",
    "angular-md5": "~0.1.7",
    "angular-base64": "~2.0.5",
    "restangular": "~1.5.1",
    "lodash": "~3.10.0"
  },
  "devDependencies": {
    "angular-mocks": "~1.4.5"
  },
  "resolutions": {
    "angular": "1.4.5",
    "angular-animate": "1.4.5"
  }
}
```

I guess the problem is `resolutions`?
https://github.com/bower/bower/issues/866

**Comment by sayanee** [comment] 2015-12-24 10:21
Thanks @banbanchs. 

Yes [it seems](http://jaketrent.com/post/bower-resolutions/) you will need to add `resolutions` in your project's `bower.json`, as opposed to this package's `bower.json`. I might be wrong, so please correct me. Will it work for you then?

**Comment by sayanee** [comment] 2016-01-10 10:56
@banbanchs can we close this? I hope the `resolutions` work?

**Comment by banbanchs** [comment] 2016-01-11 02:41
@sayanee Sorry. Ok now, thanks!

**Closed** 2016-01-11 02:43 UTC
