### ISSUE TITLE
issue when quickly goNext()

### ISSUE THREAD

**Issue by soubok** [sayanee/angularjs-pdf#70] opened 2015-11-19 17:22 UTC
Hello,
I have a pdf (1.6Mo with images) that I converted with libreOffice from a ppt.
When I ```goNext()``` quickly (with a <a> button) the content of the pdf get sometimes completely crazy (head upside and mix between pages).
Any idea where this come from ?

**Comment by simobasso** [comment] 2015-11-19 17:34
Hi @soubok, thanks. 

Can you create an example on jsbin? 

I can't reproduce.

**Comment by soubok** [comment] 2015-11-19 20:13
Issue fixed with version 1.2.4 and 1.2.5, but now I get the following error when the route is reloaded (with ```$route.reload()```):

```TypeError: pdfLoaderTask.destroy is not a function```

**Comment by soubok** [comment] 2015-11-19 20:42
testcase:
```
<!doctype html>
<html ng-app="app">
	<head>
		<script src="angular-1.4.7.min.js"></script>
		<script src="angular-route.min.js"></script>
		
		<script src="PDF.js/build/pdf.js"></script>
		<script src="angular-pdf-1.2.5.min.js"></script>

		<script>
			angular.module('app', ['ngRoute', 'pdf'])
			.config(function($routeProvider) {

				$routeProvider
				.when('/', {
					templateUrl: 'test.html',
					controller: 'testController'
				})
			})
			.controller('testController', function($scope, $route) {

				$scope.pdfUrl = 'relativity.pdf';
				$scope.reload = function() {
					
					$route.reload();	
				}
			});
		</script>

		<script type="text/ng-template" id="pdfViewer.html">
			<canvas id="pdf-canvas"></canvas>
		</script>
		
		<script type="text/ng-template" id="test.html">
			<button ng-click="reload()">reload</button>
			<div>
				<ng-pdf template-url="pdfViewer.html" canvasid="pdf-canvas" scale="1"></ng-pdf>
			</div>
		</script>
	</head>
	<body ng-view></body>
</html>
```

**Comment by simobasso** [comment] 2015-11-20 08:01
Hi @soubok, thanks for the report:

1. your example don't match [Requirements](https://github.com/sayanee/angularjs-pdf#requirements), missing the worker
1. please, can you open an example on [jsbin](http://jsbin.com/)? it's very hard help you on a copy&paste
1. next time, open a new issue for new problem

Cheers

**Comment by timtos** [comment] 2015-11-20 09:03
Hi @soubok, are you using a recent version of pdf.js? But anyway, perhaps it is a good idea to add something like if 183: if (pdfLoaderTask && (typeof pdfLoaderTask.destroy === 'function')) { 

What do you think? If we agree that this is a way to go, I would offer to make the change later.

**Comment by soubok** [comment] 2015-11-20 09:19
Hello, ( and sorry for points 2. and 3.).
I use PDF.js 1.1.469 (and my browser is the latest google chrome).
Note that the issue is not only related to reloading a route. When I leave then I come back to a view that contains angularjs-pdf, the same error appears.

**Comment by timtos** [comment] 2015-11-20 09:31
@soubok, can you then update your pdf.js? The version currently used (https://github.com/sayanee/angularjs-pdf/blob/master/example/js/lib/pdf.js) is 1.2.131. Does that already help? In line 2009 there is a destroy function defined for PDFDocumentLoadingTask ;) Keep us posted!

**Comment by soubok** [comment] 2015-11-20 10:12
Thnaks, the pdfLoaderTask.destroy error does no occurs any more with v1.2.131

**Comment by soubok** [comment] 2015-11-20 10:21
I noticed the following warning in the console with v1.2.131:
```Warning: Deprecated API usage: getDocument is called with pdfDataRangeTransport, passwordCallback or progressCallback argument```

**Comment by timtos** [comment] 2015-11-20 10:22
Good to hear. I would then say, we can close this issue.

**Closed by timtos** 2015-11-20 10:22 UTC

**Comment by timtos** [comment] 2015-11-20 10:25
@soubok, the warning you mentioned is definitely something, that has to be fixed in the future. But "the old way" is currently still fully supported. So at least for now, you can safely ignore this warning.
