### ISSUE TITLE
Render Uint8Array throw error

### ISSUE THREAD

**Issue by Clebiez** [sayanee/angularjs-pdf#110] opened 2016-03-08 10:19 UTC
Hi all,

I wan't to render a base64 PDF file with your solution !
I convert base64 to Uint8Array and I try to render it with PDFJS like the following 

        function convertDataURIToBinary(dataURI) {
          var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
          var base64 = dataURI.substring(base64Index);
          var raw = window.atob(base64File);
          var rawLength = raw.length;
          var array = new Uint8Array(new ArrayBuffer(rawLength));

          for(var i = 0; i < rawLength; i++) {
            array[i] = raw.charCodeAt(i);
          }
          return array;
        }
        var pdfAsDataUri = "data:application/pdf;base64,JVBERi0xLjUN..."; //AWESOME LENGTH
        var BASE64_MARKER = ";base64,";
        $scope.pdf = convertDataURIToBinary(pdfAsDataUri);

But when I test it, I see the following warning :

> Warning: Deprecated API usage: getDocument is called with pdfDataRangeTransport, passwordCallback or progressCallback argument

And the following error :

> TypeError: url.charAt is not a function
    at combineUrl (pdf.js:333)

Thanks to your help !

**Comment by sayanee** [comment] 2016-03-24 03:19
Hi! Have you tried [this](https://github.com/sayanee/angularjs-pdf#when-url-is-base64-or-uint8array)? Closing, but feel free to re-open if this doesn't work.

**Closed by sayanee** 2016-03-24 03:19 UTC

**Comment by johnjspiteri** [comment] 2016-12-28 21:54
In case anyone needs a working version of the process:

```javascript
var binaryImg = atob(base64String);
var binaryImgLength = binaryImg.length;
var arrayBuffer = new ArrayBuffer(binaryImgLength);
var uInt8Array = new Uint8Array(arrayBuffer);

for (var i = 0;  i < length;  i++) {
    uInt8Array[i] = binaryImg.charCodeAt(i);
}
var outputBlob = new Blob([uInt8Array], {type: 'application/pdf'});
$scope.pdfUrl = URL.createObjectURL(outputBlob);
```

**Comment by yogendrakarekar** [comment] 2017-12-15 08:47
@johnjspiteri with your code provided above it does creates a pdf but when opened in browser shows no data.
This is the url generated below
blob:http://localhost:8888/be9be94b-5750-418c-9159-43d62c0657ad

**Comment by johnjspiteri** [comment] 2017-12-19 14:22
I would love to help a fellow coder - would need more information. It can be difficult to create an online example...

It seems to me that the issue is browser related - can you test FireFox, Chrome and Safari to see if the PDF works on any of those browsers?

**Comment by jjroth** [comment] 2020-01-29 22:20
@johnjspiteri You sir are a legend! [That solution works brilliantly](https://github.com/sayanee/angularjs-pdf/issues/110#issuecomment-269547160). 

I've been searching the interwebs for days looking for a solution to this issue. You'd think being able to generate a downloadable pdf document from a base64 encoded string would be straightforward...but no! 

[This solution](https://github.com/sayanee/angularjs-pdf/issues/110#issuecomment-269547160) needs to be published far and wide to correct a lot of the misinformation out there.

Thanks so much for taking the time to post that solution!

**Comment by johnjspiteri** [comment] 2020-01-30 07:56
@jjroth you are welcome!  Happy that you are getting to where you are going... you inspired me to refactor the answer a little.
